// @ts-check
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import tailwindcss from "@tailwindcss/vite";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { identitiesRoot, identityPath, listIdentities } from "./src/lib/identities.mjs";

// Sibling identities directory, resolved with the same ../ then ../../
// discovery as identities.mjs (CI layout vs orchestration worktree).
const siblingIdentities = fileURLToPath(new URL("identities/", identitiesRoot()));

// The Tailwind entry for identity-styled pages is generated at config time:
// @source needs a real filesystem path (Tailwind's scanner does not resolve
// vite aliases), and the sibling sits at a different depth per checkout
// layout, so the path must be computed, not committed. @import lines keep the
// "#sibling" alias, which the CSS pipeline does resolve. Regenerated only
// when the content changes so mtimes stay stable for build caching.
const FONT_IMPORTS = [
  "@fontsource/inter/latin-400.css",
  "@fontsource/inter/latin-500.css",
  "@fontsource/inter/latin-600.css",
  "@fontsource/inter/latin-700.css",
  "@fontsource/plus-jakarta-sans/latin-500.css",
  "@fontsource/plus-jakarta-sans/latin-600.css",
  "@fontsource/plus-jakarta-sans/latin-700.css",
  "@fontsource/plus-jakarta-sans/latin-800.css",
  "@fontsource/lilita-one/latin-400.css",
  "@fontsource/jetbrains-mono/latin-400.css",
  "@fontsource/jetbrains-mono/latin-500.css",
  "@fontsource/jetbrains-mono/latin-600.css",
  "@fontsource/jetbrains-mono/latin-700.css",
];
const identityEntryCss = () => {
  const lines = [
    "/* Identity-page Tailwind entry. Imported ONLY by identity-styled pages, so",
    "   site.css pages never see Tailwind preflight or identity tokens.",
    "   GENERATED by astro.config.mjs - do not edit or commit. Themes and",
    "   overrides are all imported side by side like the kit's example app;",
    "   each page activates exactly one identity via data-theme + data-identity",
    "   on its <html> (the scoped token blocks win inside the page). */",
    '@import "tailwindcss";',
    ...FONT_IMPORTS.map((p) => `@import "${p}";`),
  ];
  for (const slug of listIdentities()) {
    lines.push(`@import "#sibling/${slug}/theme/theme.css";`);
    lines.push(`@import "#sibling/${slug}/overrides/overrides.css";`);
  }
  lines.push(`@source ${JSON.stringify(siblingIdentities)};`);
  return lines.join("\n") + "\n";
};
const entryCssPath = fileURLToPath(new URL("./src/styles/identity.generated.css", import.meta.url));
const nextEntryCss = identityEntryCss();
const prevEntryCss = existsSync(entryCssPath) ? readFileSync(entryCssPath, "utf8") : "";
if (prevEntryCss !== nextEntryCss) writeFileSync(entryCssPath, nextEntryCss);

// Static output only: the site deploys as plain files on R2 (no adapter, no SSR).
export default defineConfig({
  output: "static",
  markdown: {
    // Dual Shiki themes; prompt-packs and code samples render through this.
    shikiConfig: { themes: { light: "github-light", dark: "github-dark" } },
  },
  integrations: [react()],
  vite: {
    resolve: {
      alias: {
        // Identity blocks import "#sibling/<slug>/blocks/<name>" at build time.
        "#sibling": siblingIdentities,
      },
      // Sibling blocks live outside the site tree, so bare imports
      // (react, react/jsx-runtime, lucide-react) resolve by walking up
      // from the kit dir and miss the site's node_modules. dedupe pins
      // them to the site root; subpath imports dedupe by package name.
      dedupe: ["lucide-react", "react"],
    },
    plugins: [tailwindcss()],
  },
});
